[FIX] l10n_ar_ux: tag Non Monetary on new AR companies
ingadhoc/odoo-argentina pull request #1011
Opened 2024-12-27 20:13 UTC by pablohmontenegro

Task: 43407

2024-12-27 20:13 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/1011).

2025-01-02 12:31 UTC, zaoral requested changes

2025-01-02 12:31 UTC, zaoral commented on l10n_ar_ux/models/account_chart_template.py
> +        res = super()._load_data(data)
```suggestion
        res = super()._load_data(data, ignore_duplicates=ignore_duplicates)
```

2025-01-02 12:31 UTC, zaoral commented on l10n_ar_ux/models/account_chart_template.py
> +        if res.get('res.company'):
we are sure that the return is always a dictionary?

2025-01-02 12:43 UTC, pablohmontenegro commented on l10n_ar_ux/models/account_chart_template.py
> +        if res.get('res.company'):
This is the method called on "super" https://github.com/odoo/odoo/blob/18.0/addons/account/models/chart_template.py#L498 and this is the return https://github.com/odoo/odoo/blob/18.0/addons/account/models/chart_template.py#L560 . If I am not wrong, apparently it always returns a dictionary.

2025-01-03 15:20 UTC, zaoral commented
@roboadhoc r+

2025-01-03 15:25 UTC, closed without merging