[8.0][IMP][l10n_ar_account_withholding] Wizard para Exportación a SICORE
ingadhoc/odoo-argentina pull request #139
Opened 2016-10-26 15:36 UTC by ivantodorovich

Según lo hablado en https://github.com/ingadhoc/account-payment/pull/17

2016-10-26 15:48 UTC, jjscarafia requested changes

2016-10-26 15:48 UTC, jjscarafia commented on l10n_ar_account_withholding/wizard/account_withholding_sicore_wizard.py
> +        if self.company_id:
Esto ya no sería necesario porque lo hicimos obligatorio, empezaría con "tax_domain = [('company_id', '=', self.company_id.id)]"

2016-10-26 15:48 UTC, jjscarafia commented on l10n_ar_account_withholding/wizard/account_withholding_sicore_wizard.py
> +        if self.company_id:
idem acá, agregaría esto en el domain que incias arriba

2016-10-26 15:48 UTC, jjscarafia commented on l10n_ar_account_withholding/wizard/account_withholding_sicore_wizard.py
> +        domain = [['state', '=', 'posted']]
por convención (y no se si técnicamente tmb), debería ir tupla adentro del vector domain, es decir "[('state', '=', 'posted')]"

Idem para cada append abajo, sería, por ejemplo, domain.append(('date', '>=', self.from_date]))

2016-10-26 15:53 UTC, jjscarafia commented on l10n_ar_account_withholding/wizard/account_withholding_sicore_wizard_view.xml
> +                    <center>
En esta vista podrías agregar un <p> o <span> o lo que sea avisando sobre los parámetros necesario en sicore , lo que pusiste en [acá](https://github.com/ingadhoc/account-payment/pull/17) "Para que funcione, es necesario configurar el SICORE con estos parámetros de importación". Te parece? Si te parece dicha observación directamente en español para no complicar con traducción total es super exclusivo para argentina.

2016-10-26 15:53 UTC, jjscarafia commented
Grande Ivan, espectacular. Ahora que está aprobado el otro PR ya este debería dar bien (cuando hagas un nuevo push se corre todo).

2016-10-26 16:31 UTC, ivantodorovich commented
Listo!
Con eso ya estaríamos, creo.

2016-10-26 16:33 UTC, ivantodorovich commented on l10n_ar_account_withholding/wizard/account_withholding_sicore_wizard_view.xml
> +                    <center>
Agregado en la "página 1" del wizard.

2016-10-26 16:49 UTC, ivantodorovich commented
Veo que está fallando el runbot, sin embargo no entiendo por qué. Tampoco encuentro cómo ver los logs.. no tengo mucha experiencia con runbot.

En mi instancia funciona sin errores.

2016-10-27 11:35 UTC, merged

2016-10-27 11:38 UTC, jjscarafia commented
Buenísimo Ivan, el error de runbot es por un error de cache que volvió a construir sin tener en cuenta el PR aceptado del otro repo, entonces no encontraba el menú padre, haciendo click en la ruedita y en "full al logs" podes ver el log de la build. Por ej. este era el que daba error http://runbot.adhoc.com.ar/runbot/static/build/00237-139-677a08/logs/job_20_test_all.txt
Al final se puede ver el error "External ID not found in the system: account_voucher_withholding.menu_account_withholding"

Ahora te lo actualizo en tu test y confirmame cuando quieras que lo pase a producción