11.0
ingadhoc/odoo-argentina pull request #369
Opened 2019-11-28 18:48 UTC by mariodmoreno

Buenas tardes, 
Con la incorporación de las de crédito electrónico la función get_related_invoices_data() puede devolver un resultado erróneo. 
Si en
`return self.search([
                ('commercial_partner_id', '=', self.commercial_partner_id.id),
                ('company_id', '=', self.company_id.id),
                ('document_number', '=', self.origin),
                ('id', '!=', self.id),
                ('document_type_id.document_letter_id', '=', self.document_type_id.document_letter_id.id),
                ('document_type_id', '!=', self.document_type_id.id),
                ('state', 'not in',
                    ['draft', 'proforma', 'proforma2', 'cancel'])],
                limit=1)`
quitamos la el argumento `limit`, el `search` puede devolver varios comprobantes sin un orden y el problema es que puede mesclar facturas de mipyme con las tradicionales teniendo todas el mismo numero de comprobante y punto de venta.
Esto fue lo que paso en mi caso, obteniendo una nota de crédito tradicional en lugar de una factura de crédito, que era el resultado esperado.
Para resolverlo de manera rápida tome la regla de validación explicada  en el manual para desarrolladores de afip (pagina 29, erro 10040) y aplique un parámetro mas al `search`.

2019-11-28 18:53 UTC, sotolucas commented
Hola @mariodmoreno gracias por el aporte!
@jjscarafia podrías validar esta modificación?

2019-11-28 20:35 UTC, jjscarafia commented
Excelente @mariodmoreno!
Es de los casos que uno piensa que nunca se van a dar en la práctica (dos facturas con mismo número para mismo partner con distinto tipo) pero que evidentemente pasan. Imagino que solo es factible en puntos de ventas nuevos donde las facturas normales (fce) están arrancando en cero.

Como es un caso raro y como en v13 ya hay link al documento original (por ahora solo desde la NC pero estamos trabajando en odoo para las ND) es que no profundizamos en esto.

Pero ya que te pasó y avanzaste, vamos a revisarlo bien y tratar de mezclarlo.

Nuevamente, muchas gracias!

2019-11-28 20:41 UTC, jjscarafia commented
@mariodmoreno A priori veo que se agregaron los códigos del wsfe pero habría que agregar los del ws de expo (wsfex). Supongo que bono y factura con detalle deben ser los mismos.
Ahí le pedí a @zaoral que lo revise. Pero si llegas a tener más info o querer ajustar, bienvenido.

2019-11-29 12:36 UTC, mariodmoreno commented
Buenos días a todos, 
@jjscarafia Si, exactamente se nos dio este inconveniente en un punto de venta nuevo. Con respecto a wefex si habría que agregar los códigos de los comprobantes. Tengo que confirmarlo con algún contador de por acá pero creo que serian 19 para facturas 20 para nota de débito y 21 para nota de crédito, donde 20 puede tener asociada una 19 y una 21, y 21 puede tener una 19 y una 20.
Cuando me confirmen por lo agrego. Y también debería agregar algún mensaje por si el código del comprobante no esta en la lista.
Que opinan?

2019-12-02 14:29 UTC, mariodmoreno commented
Buenos dias
Agregue los códigos para wsfex y una validación que faltaba en caso de que no encuentre el tipo de comprobante.

2019-12-02 16:02 UTC, zaoral requested changes
Hola Mario! como va? 

Gracias por colaborar con este PR,  Según pude ver están bien las reglas correspondientes a WSFE ¿. Lo único que pienso haría falta es el ultimo caso de WSFEX reflejado en esta imagen para el tipo de comprobantes 19, 20 o 21

![image](https://user-images.githubusercontent.com/7593953/69973592-86912b00-1502-11ea-8e25-37ff89fa9e06.png)

Por lo cual remplazaría la linea
```python
                    ([20,21], [19, 20,21]),
```

por la siguiente que contempla los comprobantes asociados de 19, 20, 21

```python
                    ([19], [88, 89]),
                    ([20, 21], [88, 89, 19, 20, 21]),
```

Es de notar que pongo 88, 89 primero ya que son casos mas específicos para que estos sean los primeros  tomar en cuenta si existen

También te voy a pedir que hagas un cambio para pasar las reglas de python lint, es un cambio sencillo que aplica solo al estilo del código, solo debes asegurarte que tras cada coma haya un espacio, ejemplo `([2, 3], [1, 2, 3, 4, 5, 34, 39, 60, 63, 88, 991])`

Cualquier duda estoy a la orden no dudes en consultar!

2019-12-02 16:40 UTC, mariodmoreno commented
Buenas @zaoral, 
todo bien, vos?
Gracias por las correcciones. subido el fix.

2019-12-02 17:31 UTC, zaoral approved these changes
Gracias por los cambios Mario!
Aprobado el PR +1

2019-12-03 15:56 UTC, merged

2019-12-03 15:56 UTC, jjscarafia commented
Muchas gracias @mariodmoreno