[IMP] l10n_ar_account_withholding: Wizard to upload padron ARBA.
ingadhoc/odoo-argentina pull request #557
Opened 2021-11-16 14:31 UTC by nicomacr

2021-11-16 14:31 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina/pull/557).

2022-02-21 13:51 UTC, jjscarafia requested changes

2022-02-21 13:51 UTC, jjscarafia commented on l10n_ar_account_withholding/models/res_company.py
> +from odoo.exceptions import UserError,  RedirectWarning
hay dos espacios después de la ,

2022-02-21 13:51 UTC, jjscarafia commented on l10n_ar_account_withholding/models/account_tax.py
> +            ('jurisdiction_code', 'in', invoice_tags.ids),
indentar todas las tuplas del dominio

2022-02-21 13:51 UTC, jjscarafia commented on l10n_ar_account_withholding/models/res_company_jurisdiction_aliquot.py
> +    jurisdiction_code = fields.Many2many(
es un campo m2m, poner sufijo _ids

2022-02-21 13:51 UTC, jjscarafia commented on l10n_ar_account_withholding/models/res_company_jurisdiction_aliquot.py
> +    jurisdiction_code = fields.Many2many(
tiene sentido m2m? o debería ser m2o?

2022-02-21 13:51 UTC, jjscarafia commented on l10n_ar_account_withholding/models/res_company.py
> +            # if self.l10n_ar_padron_arba_date and self.l10n_ar_padron_arba_date.month != from_date.month:
está bien el redirect warning, pero si se complica directamente un warning.

El mensaje derecho en español, porque es algo super especifico argentino.

Pondría algo así:
"Obtuvimos  un error de conexión con ARBA y no encontramos padrón almacenado para las fechas dadas. Puede intentar nuevamente más tarde, cargar la alícuota manualmente en el partner o subir el archivo del padrón en bla bla bla"

2022-02-21 13:51 UTC, jjscarafia commented on l10n_ar_account_withholding/models/res_company_jurisdiction_aliquot.py
> +    _name = "res.company.jurisdiction.aliquot"
Tal vez llamaría al modelo "res.company.jurisdiction.padron"

2022-02-21 13:51 UTC, jjscarafia commented on l10n_ar_account_withholding/wizard/padron_file_wizard_views.xml
> +</odoo>
falta nueva línea, es raro que no te lo agregue solo vscode, debe faltar alguna opción

2022-02-21 13:51 UTC, jjscarafia commented on l10n_ar_account_withholding/wizard/padron_file_wizard.py
> +            })
falta nueva línea, es raro que no te lo agregue solo vscode, debe faltar alguna opción

2022-02-21 13:51 UTC, jjscarafia commented on l10n_ar_account_withholding/wizard/padron_file_wizard.py
> +    _name = "padron.file.wizard"
Abría que ver si esté wizard suma mucho o no. tal vez si mejoramos la form del modelo "res.company.jurisdiction.aliquot" direcatamente hacemos que creen y administren los archivos en esa vista. Te parece? lo probás?

2022-02-21 13:51 UTC, jjscarafia commented on l10n_ar_account_withholding/models/account_tax.py
> +                nro, alicuot_ret, alicuot_per = padron_file._get_aliquit(commercial_partner)
acá directamente crearía la alicuota, no importa si es de arba o no. Es decir, si había archivo para la jurisdiccion y encontramos resultado, directamente escribir, algo así:
```

if padron_file:
    nro, alicuot_ret, alicuot_per = padron_file._get_aliquit(commercial_partner)
    # en realidad no se si acá va el "nro" o que, debería ser algo que nos garantice que encontró registro (supongo que las aliqcuotas pueden ser 0 y en ese caso hay que crearla con cero, por eso no preguntaría if alicuot_ret)
    if nro:
        return partner.arba_alicuot_ids.sudo().create({
            'numero_comprobante': nro,
            'alicuota_retencion': float(alicuot_ret),
            'alicuota_percepcion': float(alicuot_per),
            'partner_id': commercial_partner.id,
            'company_id': company.id,
            # NOTA ver que acá supuse que vamos a transformar este dato a m2o
            'tag_id': padron_file.jurisdiction_code_id.id,
            'from_date': from_date,
            'to_date': to_date,

        })

acá todo lo anterior tal cual (creo que sin cambios)


```
                alicuot = partner.arba_alicuot_ids.sudo().create(arba_data)

2022-11-25 14:10 UTC, ica-adhoc commented
@roboadhoc r+

2022-11-25 14:50 UTC, closed without merging