[IMP]l10n_ar_ux: allow setting day currency rate
ingadhoc/odoo-argentina pull request #613
Opened 2022-05-17 14:31 UTC by pablohmontenegro

Ticket: 51807

2022-05-17 14:32 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina/pull/613).

2022-05-17 18:18 UTC, zaoral requested changes
@pablohmontenegro 

Hola Pablito,
Muchas gracias por el PR y todos los cambios, incluyo las otros mejoras y fixes que habiamos hablado.

Acá te deje abajo un par de sugerencias en el código, con respecto a tus dudas sobre las traducciones: tocaría dejarlo todo en ingles mas info ver video 
 https://drive.google.com/file/d/1pejy0peq5MjE9lnnzBe5fsOXwBKcPUuz/view

2022-05-17 18:18 UTC, zaoral commented on l10n_ar_ux/wizards/account_move_change_rate.py
> +            message = _("Currency rate changed from %s to %s") % (self.move_id.l10n_ar_currency_rate or self.move_id.computed_currency_rate, self.move_id.computed_currency_rate)
Agregaria algo mas al mensaje a publicar en la factura para que quede reflejado no solo que modificamos la cotrización sino que se cambio fue a la cotizacion del dia XX/YY/ZZZ. Dejo acá video para explicar un poco mejor la sugerencia https://drive.google.com/file/d/1oZ7lMw8qDyCYX-ri5kBY4YKevNG61nnQ/view

2022-05-17 18:18 UTC, zaoral commented on l10n_ar_ux/wizards/account_move_change_rate.py
> +            self.currency_rate = self.move_id.computed_currency_rate
El campo self.currency_rate es el del wizard en si no seria necesario setearlo. Este lo usamos solo para guardar el valor que el cliente quiere colocar en la factura

2022-05-17 18:27 UTC, pablohmontenegro commented on l10n_ar_ux/wizards/account_move_change_rate.py
> +            message = _("Currency rate changed from %s to %s") % (self.move_id.l10n_ar_currency_rate or self.move_id.computed_currency_rate, self.move_id.computed_currency_rate)
Me parece bien Kathy, lo hago entonces

2022-06-07 14:17 UTC, zaoral commented
@pablohmontenegro 
Hi Pablo, thank you for the pr.

In order to merge we need:
1. to squash all the commits in one.
2. to rebase the branch because we have some runbot in warning and errors that were not related and already sokved.
3. wait for the functional review, when we have it will be ready to go.

If you can do steps 1 and 2 in advance will be better.
Best Regards

2022-10-18 13:25 UTC, zaoral commented
@roboadhoc r+

2022-10-18 13:27 UTC, zaoral approved these changes

2022-10-19 18:09 UTC, closed without merging