[ADD] l10n_ar_account_withholding: Test ARBA
ingadhoc/odoo-argentina pull request #619
Opened 2022-06-22 19:19 UTC by ica-adhoc

tickets 50202, 52470

Add button in settings view to test ARBA connection

2022-06-22 19:19 UTC, roboadhoc commented
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina/pull/619).

2022-06-27 19:39 UTC, zaoral requested changes

2022-06-27 19:39 UTC, zaoral commented on l10n_ar_account_withholding/wizard/res_config_settings.py
> +            import pdb; pdb.set_trace()
remove import pdb

2022-06-27 19:39 UTC, zaoral commented on l10n_ar_account_withholding/models/res_company.py
> +        raise UserError('No se pudo conectar a ARBA: %s - %s' % (ws.CodigoError, message))
add_() to string "No se pudo conectar a ARBA"

2022-06-27 19:39 UTC, zaoral commented on l10n_ar_account_withholding/wizard/res_config_settings.py
> +        raise UserError('La conexión ha sido exitosa')
same. add _() at  string 'La conexión ha sido exitosa')

2022-06-30 11:04 UTC, zaoral approved these changes

2022-06-30 11:05 UTC, zaoral commented
@roboadhoc r+
@roboadhoc override=ci/argentina-ee

2022-06-30 11:05 UTC, roboadhoc commented
@zaoral, you may want to rebuild or fix this PR as it has failed CI.

2022-06-30 11:05 UTC, roboadhoc commented
I'm sorry, @zaoral. You are not allowed to override this status.

2022-06-30 11:17 UTC, nicomacr commented
@roboadhoc override=ci/argentina-ee

2022-06-30 11:18 UTC, nicomacr commented
@roboadhoc p=1

2022-06-30 11:20 UTC, closed without merging