[FIX] l10n_ar_ux: forced currency rate on invoice
ingadhoc/odoo-argentina pull request #684
Opened 2023-03-08 12:56 UTC by pablohmontenegro

Ticket: 59842
Al forzar la moneda en factura no se toma esa cotización y al volver a la moneda anterior se actualizan incorrectamente los importes de las líneas.

2023-03-08 12:57 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/684).

2023-03-15 18:33 UTC, zaoral requested changes
Hi @pablohmontenegro 
Thank you for the PRs.
pleare review the suggestion comments and the video I sent you in the ticket

2023-03-15 18:33 UTC, zaoral commented on l10n_ar_ux/models/account_move_line.py
> +            rec.currency_rate = company_currency_rate.get(from_currency.id) / rec.move_id.l10n_ar_currency_rate
```suggestion
            rec.currency_rate = 1.0 / rec.move_id.l10n_ar_currency_rate
```

2023-03-15 18:33 UTC, zaoral commented on l10n_ar_ux/wizards/account_move_change_rate.py
> +            message = _("Currency rate changed from %s to %s . Currency rate forced") % (float_round(self.move_id.computed_currency_rate, 2), float_round(self.currency_rate, 2))
```suggestion
            message = _("Currency rate changed from %s to %s . Currency rate forced") % (float_round(self.move_id.l10n_ar_currency_rate or self.move_id.computed_currency_rate, 2), float_round(self.currency_rate, 2))
```

2023-03-15 18:33 UTC, zaoral commented on l10n_ar_ux/wizards/account_move_change_rate.py
> +            message = _("Currency rate changed from %s to %s") % (float_round(self.move_id.l10n_ar_currency_rate, 2) or float_round(self.move_id.computed_currency_rate, 2), day_rate)
```suggestion
            message = _("Currency rate changed from %s to %s") % (float_round(self.move_id.l10n_ar_currency_rate or self.move_id.computed_currency_rate , 2), day_rate)
```

2023-03-23 13:32 UTC, zaoral commented
@roboadhoc r+

2023-03-23 14:15 UTC, roboadhoc commented
@pablohmontenegro @zaoral linked pull request(s) ingadhoc/account-financial-tools#390 not ready. Linked PRs are not staged until all of them are ready.

2023-03-23 14:46 UTC, closed without merging