[IMP] l10n_ar: set rate on argentinean invoices.
ingadhoc/odoo-argentina pull request #804
Opened 2024-02-15 18:53 UTC by pablohmontenegro

Ticket Adhoc: 70814

Description of the issue/feature this PR addresses: It is necessary to set afip rate to argentinean invoices.

Current behavior before PR:
Afip rate is set on argentinean invoices only if only if invoice use documents.

Desired behavior after PR is merged:
Afip rate is set on argentinean invoices.

2024-02-15 18:54 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/804).

2024-02-16 18:32 UTC, zaoral requested changes

2024-02-16 18:32 UTC, zaoral commented on l10n_ar_ux/models/account_move.py
> +        other_currency_ar_invoices = ar_invoices.filtered(lambda x: x.company_id.account_fiscal_country_id.code == "AR" and x.l10n_latam_use_documents and x.currency_id != x.company_currency_id and n
remove  x.company_id.account_fiscal_country_id.code == "AR" from other_currency_ar_invoices

2024-02-16 18:51 UTC, zaoral commented
@roboadhoc r+

2024-02-16 18:51 UTC, zaoral approved these changes

2024-02-16 19:09 UTC, closed without merging