[IMP] Add new module l10n_ar_pos
ingadhoc/odoo-argentina pull request #845
Opened 2024-05-06 12:08 UTC by maq-adhoc

2024-05-06 12:09 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/845).

2024-05-28 17:21 UTC, lef-adhoc approved these changes

2024-06-04 16:15 UTC, matiasperalta1 requested changes

2024-06-04 16:15 UTC, matiasperalta1 commented on l10n_ar_pos/__manifest__.py
> +    'version': '1.0',
version correcta o va 16.0.1.0.0?

2024-06-04 16:15 UTC, matiasperalta1 commented on l10n_ar_pos/__manifest__.py
> +        #'views/templates.xml',
eliminar comentario

2024-06-04 16:15 UTC, matiasperalta1 commented on l10n_ar_pos/demo/point_of_sale_demo.xml
> +        <record model="pos.config"  context="{'allowed_company_ids': [ref('l10n_ar.company_ri')]}" id="pos_config_l10n_ar">
Hay un warning en la creación de la build de runbot. Viene de acá

2024-06-04 16:15 UTC, matiasperalta1 commented on l10n_ar_pos/__manifest__.py
> +    'auto_install': True,
Misdmo que el otro módulo. Me parece que acá se setea como falso y luego desde adhoc module en la versión se setea la opción correcta en el campo "Auto Installation Policy"

2024-06-04 16:15 UTC, matiasperalta1 commented on l10n_ar_pos/template.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Si no se va a usar este xml eliminarlo puede ser en otro commit así queda por las dudas

2024-08-06 16:45 UTC, maq-adhoc commented on l10n_ar_pos/__manifest__.py
> +    'auto_install': True,
Viene de odoo 17 es un backport, mantengo alienado

2024-08-08 14:02 UTC, matiasperalta1 commented
@roboadhoc r+

2024-08-08 14:07 UTC, closed without merging