[FIX] l10n_ar_ux: Recompute the commercial partner for edit de contact form in portal
ingadhoc/odoo-argentina pull request #850
Opened 2024-05-10 17:24 UTC by mem-adhoc

Ticekt: 73707

2024-05-10 17:24 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/850).

2024-07-11 19:02 UTC, pablohmontenegro requested changes

2024-07-11 19:02 UTC, pablohmontenegro commented on l10n_ar_ux/controllers/portal.py
> +            partner.l10n_latam_identification_type_id = request.env['l10n_latam.identification.type'].browse(ident)
Hola @mem-adhoc todo bien? habría que ver por que se pierde el dato de commercial_partner_id, la responsabilidad y el tipo de identificación. Puede ser que eso se borre acá https://github.com/ingadhoc/odoo-argentina/pull/850/files#diff-51ca5a4b1035aaa9b2c6feef07a8f4b64843d69641e03e98a7734c53da076eb8R40-R43 entonces corresponda borrar directamete esas líneas? no lo se, consulto por las dudas, habría que ver por qué existe esa sección en el link que te mencioné

2024-07-11 19:02 UTC, pablohmontenegro commented on l10n_ar_ux/controllers/portal.py
> +            'identification_type': partner.l10n_latam_identification_type_id.id or False,
por qué sería necesario agregar esto?

2024-07-11 19:02 UTC, pablohmontenegro commented on l10n_ar_ux/controllers/portal.py
> +            'partner_can_edit_vat': partner.can_edit_vat()})
por qué sería necesario agregar esto?

2024-07-12 14:45 UTC, zaoral requested changes

2024-07-12 14:45 UTC, zaoral commented on l10n_ar_ux/controllers/portal.py
> +            'responsibility_type': partner.l10n_ar_afip_responsibility_type_id.id or False,
```suggestion
            'l10n_ar_afip_responsibility_type_id': partner.l10n_ar_afip_responsibility_type_id.id or post.get('l10n_ar_afip_responsibility_type_id')
```

2024-07-12 14:45 UTC, zaoral commented on l10n_ar_ux/controllers/portal.py
> +            'identification_type': partner.l10n_latam_identification_type_id.id or False,
same
            'l10n_latam_identification_type_id': partner.l10n_latam_identification_type_id.id or post.get('l10n_latam_identification_type_id'),

2024-07-12 14:45 UTC, zaoral commented on l10n_ar_ux/controllers/portal.py
> +            partner.l10n_latam_identification_type_id = request.env['l10n_latam.identification.type'].browse(ident)
1. check if the elements came in **post
2. verificar el if not error or if error (check remove it temporally to see what it happens.
3. delete set of values on database partner.field = value

2024-07-12 14:45 UTC, zaoral commented on l10n_ar_ux/views/portal_templates.xml
> +                            <option t-att-value="afip_res.id" t-att-selected="afip_res.id == responsibility_type and 'selected' or None">
delete

2024-07-12 14:45 UTC, zaoral commented on l10n_ar_ux/views/portal_templates.xml
> +                            <option t-att-value="document_identification.id"  t-att-selected="document_identification.id == identification_type and 'selected' or None">
delete

2024-07-25 19:12 UTC, zaoral requested changes

2024-07-25 19:12 UTC, zaoral commented on l10n_ar_ux/controllers/portal.py
nuevo método nombre sugerido **values_preprocess_ar** símil al que existe en website_sale en donde pasa a enteros los campos que son relacionales. en nuestro caso solo para los campos document type y identification type

https://github.com/odoo/odoo/blob/16.0/addons/website_sale/controllers/main.py#L1057-L1072

2024-07-25 19:12 UTC, zaoral commented on l10n_ar_ux/controllers/portal.py
aca, antes de llamar al super, hacer  llamada al nuevo values_preprocess_ar asi vemos que los campos esten bien y queden storeados. solo hacerlo en caso que hay valores por escribir

```suggestion
   if post and request.httprequest.method == 'POST':
         post = self.values_preprocess_ar(post)
```

2024-07-25 19:12 UTC, zaoral commented on l10n_ar_ux/controllers/portal.py
> +        partner._compute_commercial_partner()
esto lo quitaria, porque creo que no es necesario

2024-07-25 19:12 UTC, zaoral commented on l10n_ar_ux/controllers/portal.py
> +        #     partner.l10n_latam_identification_type_id = request.env['l10n_latam.identification.type'].browse(ident)
esto que esta comentado lo borraria, porque en si al pre procesar los valores la llamada del super() se encargara de escribirlos correctamente en el partner

2024-07-25 19:12 UTC, zaoral commented on l10n_ar_ux/controllers/portal.py
> +            'l10n_latam_identification_type_id': post.get('l10n_latam_identification_type_id'),
cambiarle el nombre a uno distinto al del campo
para que asi podamos idenficiar entre el input del form, y el valor real
```suggestion
            'afip_responsibility': post.get('l10n_ar_afip_responsibility_type_id'),
            'lidentification_type': post.get('l10n_latam_identification_type_id'),
```

2024-07-25 19:12 UTC, zaoral commented on l10n_ar_ux/views/portal_templates.xml
> +                            <option t-att-value="document_identification.id" t-att-selected="document_identification.id == int(l10n_latam_identification_type_id) if l10n_latam_identification_type_id
```suggestion
                            <option t-att-value="document_identification.id" t-att-selected="document_identification.id == int(lidentification_type) if lidentification_type else document_identification.id == partner.l10n_latam_identification_type_id.id">
```

2024-07-25 19:12 UTC, zaoral commented on l10n_ar_ux/views/portal_templates.xml
> +                            <option t-att-value="afip_res.id" t-att-selected="afip_res.id == int(l10n_ar_afip_responsibility_type_id) if l10n_ar_afip_responsibility_type_id else afip_res.id == partne
```suggestion
                            <option t-att-value="afip_res.id" t-att-selected="afip_res.id == int(afip_responsibility) if afip_responsibility else afip_res.id == partner.l10n_ar_afip_responsibility_type_id.id">
```

2024-08-09 13:50 UTC, zaoral requested changes
@mem-adhoc 

Varias cositas a revisar:

- evitar casteo en vista
- que el preparar values sea solo para los campos argentinos
- tema de confusion con respecto a como muestra los campos cuando hay errores.
- tema indentación. habías dejado un par de tabs, ver que este bien
- lineas en blanco agregas y eliminadas, remover y dejar solo los cambios reales y necesarios

2024-10-21 12:46 UTC, zaoral requested changes

2024-10-21 12:46 UTC, zaoral commented on l10n_ar_ux/controllers/portal.py
> +        ar_camp = ['vat', 'l10n_ar_afip_responsibility_type_id', 'l10n_latam_identification_type_id', 'commercial_partner_id']
```suggestion
        ar_camp = ['l10n_ar_afip_responsibility_type_id', 'l10n_latam_identification_type_id']
```

2024-10-21 12:46 UTC, zaoral commented on l10n_ar_ux/controllers/portal.py
> +    def values_preprocess_ar(self, values):
add dosctirng

2024-10-21 12:46 UTC, zaoral commented on l10n_ar_ux/controllers/portal.py
> +
```suggestion


```

2024-10-21 13:53 UTC, mem-adhoc commented on l10n_ar_ux/controllers/portal.py
> +
Esto lo necesitamos ya que nosotros estamos pisando la data aca https://github.com/ingadhoc/odoo-argentina/pull/850/files#diff-51ca5a4b1035aaa9b2c6feef07a8f4b64843d69641e03e98a7734c53da076eb8R60, si no tenemos estas lineas, se nos va a borrar la info del post

2024-10-21 13:55 UTC, mem-adhoc commented on l10n_ar_ux/controllers/portal.py
> +        ar_camp = ['vat', 'l10n_ar_afip_responsibility_type_id', 'l10n_latam_identification_type_id', 'commercial_partner_id']
Con respecto al vat tenes razon, pero si no procesamos el commercial_partner_id nos da error, ya que el commercial partner es un many2one que tenemos que procesar!

2024-10-21 19:03 UTC, zaoral commented
NOTA: Segun hablado con Maxi en slack ya esta modificado y probado el PR. procedemos a hacer rebase porque esta out of date y a mezclar

2024-10-21 19:08 UTC, zaoral approved these changes

2024-10-21 19:08 UTC, zaoral commented on l10n_ar_ux/controllers/portal.py
> +            post = self.values_preprocess_ar(post)
post.update(self.values_preprocess_ar(post))

2024-10-21 19:08 UTC, zaoral commented on l10n_ar_ux/controllers/portal.py
> +
retunre new_values

2024-10-21 19:08 UTC, zaoral commented
@roboadhoc r+

2024-10-21 19:33 UTC, closed without merging