[IMP] l10n_ar_account_withholding: cambiar nombre a setting de ganancias en ajustes
ingadhoc/odoo-argentina pull request #863
Opened 2024-06-11 13:31 UTC by pablohmontenegro

Tarea: 39554

2024-06-11 13:32 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/863).

2024-06-14 18:09 UTC, zaoral requested changes

2024-06-14 18:09 UTC, zaoral commented on l10n_ar_account_withholding/models/res_company.py
> +        'Regímenes de ganancias en los que usualmente retiene',
```suggestion
        'Regímenes que usualmente retiene',
```

2024-06-14 18:35 UTC, zaoral commented
@roboadhoc r+

2024-06-14 18:46 UTC, closed without merging