[FIX] l10n_ar_bank: Corregimos los datos del banco ITAU
ingadhoc/odoo-argentina pull request #864
Opened 2024-06-12 17:07 UTC by mem-adhoc

Ticket: 76130
El banco Macro compro el banco ITAU

2024-06-12 17:07 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/864).

2024-06-14 13:48 UTC, zaoral requested changes

2024-06-14 13:48 UTC, zaoral commented on l10n_ar_bank/data/res_bank.xml
> +        <record model='res.bank' id='44089'>
ident

2024-06-14 18:02 UTC, zaoral approved these changes

2024-06-14 18:02 UTC, zaoral commented
@roboadhoc r+

2024-06-14 18:05 UTC, closed without merging