[FIX] l10n_latam_invoice_document: document type changed on invoice that was posted.
ingadhoc/odoo-argentina pull request #879
Opened 2024-08-01 18:12 UTC by pablohmontenegro

Version: 13

Description of the issue/feature this PR addresses:

Argentinean localization: if a customer invoice with partner with "IVA Responsable Inscripto" AFIP Responsibility is confirmed, then reset to draft and changed the partner to one with "Consumidor Final" AFIP Responsibility, then "Document Type" field is changed and this is not the desired behavior because that field is readonly when the invoice was posted. Compute method should not overried the document type if the invoice was posted before. If it does then an incosistency will occurr because the name, document type and sequence will not match. A new sequence non-real will be used. Also the user it is not aware is happening because the field is readonly.

Video showing how to replicate the bug:

https://drive.google.com/file/d/1D4uqNnXMkguS813NiLl9td4_f_TJ35Xf/view

Steps to reproduce:

Log in with admin on runbot odoo enterprise 16 instance and install l10n_ar_edi (Argentinean Electronic Invoicing) module.

Take position on company "Responsable Inscripto"

Go to "Accounting / Customers / Invoices" and create a new customer invoice with customer "ADHOC SA" (this partner has "IVA Responsable Inscripto" AFIP Responsibility), with a sale journal "Pre-printed Invoice" AFIP POS System (i.e Ventas Preimpreso), add an invoice line and confirm it.

Reset to draft the invoice mentioned in step 3 (now journal and document type are readonly fields), change customer to "Consumidor Final Anónimo" (this partner has "Consumidor Final" AFIP Responsibility) and save. Check that the document type has changed from "(1) FACTURAS A" to "(6) FACTURAS B" and this is not the desired behavior because is a readonly field now because the invoice was posted before.

Current behavior before PR:

When a customer invoice with customern with "IVA Responsable Inscripto" AFIP Responsibility is confirmed, then reset to draft and changed the customer to one with "Consumidor Final" AFIP Responsibility, then "Document Type" field is changed and this is not the desired behavior because that field is readonly when the invoice was posted.

Desired behavior after PR is merged:

When a customer invoice with customer with "IVA Responsable Inscripto" AFIP Responsibility is confirmed, then reset to draft and changed the customer to one with "Consumidor Final" AFIP Responsibility, then "Document Type" field is not changed.

Ticket Adhoc side: 77058

Task latam: 1235

2024-08-01 18:13 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/879).

2024-08-06 12:59 UTC, zaoral requested changes

2024-08-06 12:59 UTC, zaoral commented on l10n_ar_ux/models/account_move.py
> +        super(AccountMove, moves_without_l10n_latam_document_type)._compute_l10n_latam_document_type()
```suggestion
        sale_posted_before = self.filtered(lambda x: x.move_type in ['out_invoice', 'out_refund'] and x.l10n_latam_document_number)
        super(AccountMove, self - sale_posted_before)._compute_l10n_latam_document_type()
```

2024-08-07 20:51 UTC, zaoral commented
@roboadhoc r+

2024-08-07 20:55 UTC, closed without merging