[IMP] l10n_ar_account_withholding_cba: new module
ingadhoc/odoo-argentina pull request #900
Opened 2024-09-02 19:15 UTC by pablohmontenegro

2024-09-02 19:16 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/900).

2024-10-30 12:20 UTC, pablohmontenegro commented on l10n_ar_account_withholding_cba/models/account_tax.py
> +    ratio = fields.Float(required=True, default=100, help="Ratio to apply to tax base amount")
Para quien haga review técnico me queda dudas si debe ser requerido, o si debemos hacer que siempre sea 100 y hacemos que sea solo visible para argentina

2024-11-08 14:58 UTC, zaoral requested changes

2024-11-08 14:58 UTC, zaoral commented on l10n_ar_account_withholding_cba/README.rst
> +=============================
the length of the === should be the same of the text, if not will get a warning un runbot for error in the manifest rst file

2024-11-08 14:58 UTC, zaoral commented on l10n_ar_account_withholding_cba/models/account_tax.py
> +        return res
return  super()._compute_amount(base_amount, price_unit, quantity, product, partner=partner, fixed_multiplicator=fixed_multiplicator)

2024-11-08 14:58 UTC, zaoral commented on l10n_ar_account_withholding_cba/models/account_tax.py
> +        res = super()._compute_amount(base_amount, price_unit, quantity, product, partner=partner, fixed_multiplicator=fixed_multiplicator)
you do not change result of the super, so i think you can remove it here and simple call it at the return

2024-11-08 15:16 UTC, zaoral commented on l10n_ar_account_withholding_ratio/views/account_tax_view.xml
> +                <field name="ratio" attrs="{'invisible':[('country_code', '!=', 'AR')]}"/>
```suggestion
                <div attrs="{'invisible':[('country_code', '!=', 'AR')]}">
                    <label name="ratio">
                    <field name="ratio"/>
                    %
                </div>
```

2024-11-08 16:03 UTC, zaoral approved these changes
rename to l10n_ar_account_withh

2024-11-08 16:04 UTC, zaoral commented
@roboadhoc r+

2024-11-08 16:20 UTC, closed without merging