[FIX] l10n_ar_purchase: Agregamos traducciones
ingadhoc/odoo-argentina pull request #917
Opened 2024-10-01 15:57 UTC by mem-adhoc

2024-10-01 16:00 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/917).

2024-10-03 20:59 UTC, zaoral requested changes

2024-10-03 20:59 UTC, zaoral commented on l10n_ar_purchase/i18n/es.po
>  msgid "Request for Quotation"
need to update manifest version to run update of the module and synchronize new translation terms?

2024-10-03 20:59 UTC, zaoral commented on l10n_ar_purchase/i18n/es.po
> +msgstr "Fecha de aprobacion"
re order this terms where they should be.
To do this you can load this into a local database for example and then using Odoo tools export again the translations. apply for both files

2024-10-03 20:59 UTC, zaoral commented on l10n_ar_purchase/i18n/es.po
> +msgstr "Fecha de vencimiento"
missing : on translation
```suggestion
msgstr "Fecha de vencimiento:"
```

2024-10-03 20:59 UTC, zaoral commented on l10n_ar_purchase/i18n/es.po
> +msgstr "Fecha de aprobacion"
same of above
```suggestion
msgstr "Fecha de aprobacion;"
```

2024-10-04 20:17 UTC, zaoral commented
@roboadhoc r+

2024-10-04 20:21 UTC, closed without merging