[FIX] l10n_ar_ux: uninstall hooks for monkey patches
ingadhoc/odoo-argentina pull request #920
Opened 2024-10-03 20:28 UTC by cav-adhoc

2024-10-03 20:29 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/920).

2024-10-04 13:16 UTC, maq-adhoc requested changes
Vemos si funciona

2024-10-04 13:16 UTC, maq-adhoc commented on l10n_ar_ux/hooks.py
> +from odoo.addons.l10n_ar.models.account_fiscal_position import AccountFiscalPosition
from odoo.addons.l10n_ar.models.account_fiscal_position.AccountFiscalPosition import _get_fiscal_position as _get_fiscal_position_original

2024-10-04 13:16 UTC, maq-adhoc commented on l10n_ar_ux/hooks.py
> +    AccountFiscalPosition._get_fiscal_position = _get_fiscal_position
AccountFiscalPosition._get_fiscal_position = _get_fiscal_position_original

2024-11-19 20:11 UTC, cav-adhoc commented
sigue en https://github.com/ingadhoc/odoo-argentina/pull/952

2024-11-19 20:11 UTC, closed without merging