WIP
ingadhoc/odoo-argentina pull request #935
Opened 2024-10-24 14:02 UTC by jjscarafia

2024-10-24 14:03 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/935).

2024-11-21 16:56 UTC, maq-adhoc requested changes

2024-11-21 16:56 UTC, maq-adhoc commented on l10n_ar_account_withholding/views/account_payment_view.xml
> +                <attribute name="invisible">state != 'draft' or (partner_type == 'supplier' and need_withholding_recompute)</attribute>
Podriamos hacerlo asi? 
eso permite que si tenemos que heredar el invisible de otro modulo también podamos hacerlo
```xml
<attribute name="invisible" add=" or (partner_type == 'supplier' and need_withholding_recompute)"  separator=" " />

```
a

2024-11-21 16:56 UTC, maq-adhoc commented on l10n_ar_withholding_ux/migrations/17.0.1.6.0/post-migration.py
> +    logger.info('Forzamos la actualización de la vista res_company_setting.xml en módulo account payment group.')
account payment pro!!!

![image](https://github.com/user-attachments/assets/3499c286-315c-495c-8d2c-9154f3f35466)

2024-11-21 17:26 UTC, rov-adhoc commented on l10n_ar_account_withholding/views/account_payment_view.xml
> +                <attribute name="invisible">state != 'draft' or (partner_type == 'supplier' and need_withholding_recompute)</attribute>
Listo filo @maq-adhoc

2024-11-21 17:26 UTC, rov-adhoc commented on l10n_ar_withholding_ux/migrations/17.0.1.6.0/post-migration.py
> +    logger.info('Forzamos la actualización de la vista res_company_setting.xml en módulo account payment group.')
@maq-adhoc listo

2024-11-22 15:56 UTC, rov-adhoc commented
@roboadhoc r+

2024-11-22 16:32 UTC, closed without merging