[MIG] l10n_ar_purchase: Migration to 18.0
ingadhoc/odoo-argentina pull request #938
Opened 2024-10-29 13:43 UTC by pablohmontenegro

2024-10-29 13:43 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/938).

2024-11-19 17:56 UTC, pablohmontenegro commented on l10n_ar_purchase/views/purchase_report_templates.xml
> +        <xpath expr="//t[@t-set='layout_document_title']" position="replace">
```suggestion
        <t t-set='layout_document_title']" position="replace">
```

2024-11-19 17:57 UTC, pablohmontenegro commented on l10n_ar_purchase/views/purchase_report_templates.xml
> +        <xpath expr="//t[@t-set='layout_document_title']" position="replace">
```suggestion
        <t t-set='layout_document_title' position="replace">
```

2024-11-19 17:57 UTC, pablohmontenegro commented on l10n_ar_purchase/views/purchase_report_templates.xml
> +        </xpath>
```suggestion
        </t>
```

2024-11-19 17:59 UTC, pablohmontenegro commented on l10n_ar_purchase/views/purchase_report_templates.xml
> +        <xpath expr="//div[hasclass('mt-4')]/t[@t-set='layout_document_title']" position="replace">
```suggestion
        <t t-set='layout_document_title' position="replace">
```

2024-11-19 18:06 UTC, mem-adhoc requested changes

2024-11-19 18:06 UTC, mem-adhoc commented on l10n_ar_purchase/views/purchase_report_templates.xml
> +        <xpath expr="//t[@t-set='layout_document_title']" position="replace">
```suggestion
        <t t-set='layout_document_title' position="replace">
```

2024-11-19 18:06 UTC, mem-adhoc commented on l10n_ar_purchase/views/purchase_report_templates.xml
> +        </xpath>
```suggestion
        </t>
```

2024-11-19 18:06 UTC, mem-adhoc commented on l10n_ar_purchase/views/purchase_report_templates.xml
> +        </xpath>
idem

2024-11-19 19:06 UTC, zaoral approved these changes
@roboadhoc r+

2024-11-19 19:22 UTC, closed without merging