[IMP] l10n_ar_withholding_ux: eliminar botón de retenciones automáticas.
ingadhoc/odoo-argentina pull request #943
Opened 2024-11-04 19:51 UTC by pablohmontenegro

Tarea: 44518

2024-11-04 19:52 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/943).

2024-11-25 12:54 UTC, zaoral requested changes

2024-11-25 12:54 UTC, zaoral commented on l10n_ar_withholding_ux/__manifest__.py
>          'security/ir.model.access.csv',
remove import wizarrds from module/__init__.py

2024-11-25 12:54 UTC, zaoral commented on l10n_ar_withholding_ux/models/account_payment.py
> -        self.filtered('company_id.automatic_withholdings').compute_withholdings()
lets wait for maru feedback
* if we need to let the force update then change the line to `self.compute_withholdings()`

2024-11-25 12:57 UTC, closed without merging