[FIX] l10n_ar_account_withholding: Percepciones en facturas de cliente
ingadhoc/odoo-argentina pull request #944
Opened 2024-11-06 13:06 UTC by pablohmontenegro

En facturas de cliente necesitamos que se calculen las percepciones aplicadas sin necesidad de establecer la fecha en la factura, entonces establecemos la fecha para que se calculen dichas percepciones. Este es el mismo comportamiento que estaba en 16. Ticket: 82729
Este pr reemplaza este fw https://github.com/ingadhoc/odoo-argentina/pull/849 que había sido cerrado.

2024-11-06 13:06 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/944).

2024-11-07 13:34 UTC, zaoral requested changes

2024-11-07 13:34 UTC, zaoral commented on l10n_ar_account_withholding/models/account_tax.py
>              date = self._context.get('invoice_date', fields.Date.context_today(self))
```suggestion
            date = self._context.get('invoice_date') or fields.Date.context_today(self)
```

2024-11-08 17:40 UTC, jjscarafia commented
@roboadhoc r+

2024-11-08 17:44 UTC, closed without merging