[FIX] l10n_ar_withholding_ux: set valid default_type_tax_use param value in withholding tax form
ingadhoc/odoo-argentina pull request #994
Opened 2024-12-17 11:21 UTC by jue-adhoc

2024-12-17 11:21 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina/pull/994).

2024-12-19 13:17 UTC, zaoral requested changes

2024-12-19 13:17 UTC, zaoral commented on l10n_ar_withholding_ux/views/account_tax_view.xml
> -        <field name="context">{'search_default_customer': True, 'search_default_supplier': True, 'default_type_tax_use': 'supplier', 'active_test': False}</field>
add other field with default supplier
and update the manifest

2024-12-19 13:18 UTC, zaoral commented on l10n_ar_withholding_ux/views/account_tax_view.xml
> -        <field name="context">{'search_default_customer': True, 'search_default_supplier': True, 'default_type_tax_use': 'supplier', 'active_test': False}</field>
https://github.com/ingadhoc/odoo-argentina/blob/279ee282fc86fdfee2b52bfad857c105178857ad/l10n_ar_account_withholding/models/account_tax.py#L26

this one also change it
ask to Filo

2024-12-26 13:09 UTC, zaoral commented
@roboadhoc r+

2024-12-26 13:12 UTC, closed without merging